name: A workflow to create a Dockerfile
on: push

jobs:
  build:
    name: Build Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./Docker101/Docker_tf/
